"""add morning weight to segmented checkins

Revision ID: 24aa4c7c60c3
Revises: c77caec23789
Create Date: 2026-02-16 19:43:24.592222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24aa4c7c60c3'
down_revision = 'c77caec23789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('morning_weight_kg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_column('morning_weight_kg')

    # ### end Alembic commands ###
