"""add unit system preference to profile

Revision ID: 7c5634b8db32
Revises: d880ac2199df
Create Date: 2026-02-16 18:43:28.663071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5634b8db32'
down_revision = 'd880ac2199df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_system', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('unit_system')

    # ### end Alembic commands ###
