"""init

Revision ID: 8db42a77f097
Revises: 
Create Date: 2026-02-16 17:20:25.052484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db42a77f097'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('daily_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('focus', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('anxiety', sa.Integer(), nullable=True),
    sa.Column('productivity', sa.Integer(), nullable=True),
    sa.Column('accomplishments', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('workout_timing', sa.String(length=120), nullable=True),
    sa.Column('workout_intensity', sa.Integer(), nullable=True),
    sa.Column('alcohol_drinks', sa.Float(), nullable=True),
    sa.Column('symptoms', sa.JSON(), nullable=True),
    sa.Column('digestion', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_daily_checkin_user_day')
    )
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checkins_day'), ['day'], unique=False)

    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eaten_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('portion_notes', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meals_eaten_at'), ['eaten_at'], unique=False)

    op.create_table('substances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('substances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_substances_taken_at'), ['taken_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_substances_taken_at'))

    op.drop_table('substances')
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meals_eaten_at'))

    op.drop_table('meals')
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checkins_day'))

    op.drop_table('daily_checkins')
    op.drop_table('users')
    # ### end Alembic commands ###
