"""add segmented daily checkin fields

Revision ID: c77caec23789
Revises: 9d6396d3d607
Create Date: 2026-02-16 19:21:20.590496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77caec23789'
down_revision = '9d6396d3d607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('morning_energy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('morning_focus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('morning_mood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('morning_stress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('morning_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('midday_energy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('midday_focus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('midday_mood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('midday_stress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('midday_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evening_energy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evening_focus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evening_mood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evening_stress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('evening_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_checkins', schema=None) as batch_op:
        batch_op.drop_column('evening_notes')
        batch_op.drop_column('evening_stress')
        batch_op.drop_column('evening_mood')
        batch_op.drop_column('evening_focus')
        batch_op.drop_column('evening_energy')
        batch_op.drop_column('midday_notes')
        batch_op.drop_column('midday_stress')
        batch_op.drop_column('midday_mood')
        batch_op.drop_column('midday_focus')
        batch_op.drop_column('midday_energy')
        batch_op.drop_column('morning_notes')
        batch_op.drop_column('morning_stress')
        batch_op.drop_column('morning_mood')
        batch_op.drop_column('morning_focus')
        batch_op.drop_column('morning_energy')
        batch_op.drop_column('sleep_notes')

    # ### end Alembic commands ###
