"""add auth and user profiles

Revision ID: d880ac2199df
Revises: 8db42a77f097
Create Date: 2026-02-16 17:43:32.805919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd880ac2199df'
down_revision = '8db42a77f097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('biological_sex', sa.String(length=32), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('general_health_rating', sa.Integer(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('known_sleep_issues', sa.Text(), nullable=True),
    sa.Column('family_history_flags', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('supplements', sa.Text(), nullable=True),
    sa.Column('resting_blood_pressure', sa.String(length=32), nullable=True),
    sa.Column('fitness_level', sa.String(length=32), nullable=True),
    sa.Column('typical_sleep_duration_hours', sa.Float(), nullable=True),
    sa.Column('work_type', sa.String(length=32), nullable=True),
    sa.Column('work_stress_baseline', sa.Integer(), nullable=True),
    sa.Column('typical_alcohol_frequency', sa.String(length=120), nullable=True),
    sa.Column('caffeine_baseline', sa.String(length=120), nullable=True),
    sa.Column('nicotine_use', sa.String(length=120), nullable=True),
    sa.Column('recreational_drug_use', sa.String(length=120), nullable=True),
    sa.Column('diet_style', sa.String(length=120), nullable=True),
    sa.Column('food_intolerances', sa.Text(), nullable=True),
    sa.Column('food_sensitivities', sa.Text(), nullable=True),
    sa.Column('typical_meal_timing', sa.String(length=120), nullable=True),
    sa.Column('cravings_patterns', sa.String(length=255), nullable=True),
    sa.Column('baseline_mood', sa.Integer(), nullable=True),
    sa.Column('baseline_anxiety', sa.Integer(), nullable=True),
    sa.Column('baseline_focus', sa.Integer(), nullable=True),
    sa.Column('energy_consistency', sa.String(length=32), nullable=True),
    sa.Column('attention_issues', sa.String(length=255), nullable=True),
    sa.Column('emotional_volatility', sa.String(length=32), nullable=True),
    sa.Column('burnout_history', sa.Text(), nullable=True),
    sa.Column('primary_goal', sa.String(length=255), nullable=True),
    sa.Column('secondary_goals', sa.Text(), nullable=True),
    sa.Column('time_horizon', sa.String(length=120), nullable=True),
    sa.Column('great_day_definition', sa.Text(), nullable=True),
    sa.Column('chronotype', sa.String(length=32), nullable=True),
    sa.Column('digestive_sensitivity', sa.Text(), nullable=True),
    sa.Column('stress_reactivity', sa.Text(), nullable=True),
    sa.Column('social_pattern', sa.Text(), nullable=True),
    sa.Column('screen_time_evening_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('full_name')

    op.drop_table('user_profiles')
    # ### end Alembic commands ###
