"""add favorite meal ingredients

Revision ID: e68a68792a9a
Revises: 24aa4c7c60c3
Create Date: 2026-02-17 12:04:23.833441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68a68792a9a'
down_revision = '24aa4c7c60c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_meals', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
